ALTER TABLE Author MODIFY AuthorId INT AUTO_INCREMENT;
ALTER TABLE Book MODIFY BookId INT AUTO_INCREMENT;
ALTER TABLE Genre MODIFY GenreId INT AUTO_INCREMENT;
ALTER TABLE BookonomieUser MODIFY UserId INT AUTO_INCREMENT;
